default:
  image: eclipse-temurin:17-jdk-alpine

stages:
  - build
  - test
  - publish

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew
  - echo "Java version:"
  - java -version
  - echo "Gradle version from wrapper:"
  - ./gradlew --version

build:
  stage: build
  script:
    - ./gradlew build
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'

test:
  stage: test
  script:
    - ./gradlew check
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'
  needs: ["build"]

publish:
  stage: publish
  script:
    - ./gradlew publish
  rules:
    - if: '$CI_COMMIT_TAG'
  needs: ["test"]

publish_to_portal:
  stage: publish
  script:
    - >
      ./gradlew publishPlugins
      -Pgradle.publish.key=$GRADLE_PUBLISH_KEY
      -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
  needs: [ "test" ]